// Code generated by templ DO NOT EDIT.

package turbo

import "github.com/a-h/templ"
import "context"
import "io"

func TurboStream(opts TurboStreamOptions) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		_, err = io.WriteString(w, "<turbo-stream")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, " action=")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, templ.EscapeString(opts.Action.String()))
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, " target=")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, templ.EscapeString(opts.Target))
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "\"")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, ">")
		if err != nil {
			return err
		}
		if opts.Contents != nil {
			_, err = io.WriteString(w, "<template>")
			if err != nil {
				return err
			}
			err = (*opts.Contents).Render(ctx, w)
			if err != nil {
				return err
			}
			_, err = io.WriteString(w, "</template>")
			if err != nil {
				return err
			}
		}
		_, err = io.WriteString(w, "</turbo-stream>")
		if err != nil {
			return err
		}
		return err
	})
}

